[project]
name = "acoustic-knowledge-discovery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "3.11.12"
dependencies = [
    "pyha-analyzer",
]

[tool.uv.sources]
pyha-analyzer = { git = "https://github.com/UCSD-E4E/pyha-analyzer-2.0.git" }
